safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      ./input/
destination: ./output/
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

